meta_product_name: "Mon futur appartement"
meta_title: "Mon futur appartement"
meta_description: "Gérez les différentes pièces et meubles de votre futur appartement"
meta_image: "home_banner.jpg" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
